const PACK = [
  ["what is api rate limit", "API rate limit is the maximum number of requests allowed in a given time window."],
  ["what is webhook", "A webhook is an HTTP callback triggered automatically when an event happens."],
  ["difference between http and https", "HTTPS is HTTP secured with TLS encryption for privacy and integrity."],
  ["what is dns", "DNS translates domain names into IP addresses so devices can connect to servers."],
  ["what is ssl certificate", "An SSL/TLS certificate verifies identity and enables encrypted HTTPS connections."],
  ["how to write bug report", "Include steps to reproduce, expected result, actual result, environment, and evidence."],
  ["what is root cause analysis", "Root cause analysis finds the underlying reason behind a problem, not just symptoms."],
  ["what is incident response", "Incident response is the process of detecting, containing, resolving, and reviewing incidents."],
  ["what is qa testing", "QA testing checks software quality before release through planned test cases."],
  ["what is smoke test", "Smoke test is a quick check that core features work after a new build."],
  ["what is canary release", "Canary release deploys changes gradually to a small user group before full rollout."],
  ["what is feature flag", "Feature flags let teams enable or disable features without redeploying code."],
  ["what is product backlog", "Product backlog is a prioritized list of features, fixes, and improvements."],
  ["what is sprint planning", "Sprint planning defines what work to deliver in a sprint and how to do it."],
  ["what is standup meeting", "A standup is a short daily sync on progress, plans, and blockers."],
  ["how to manage project risk", "Identify risks early, rank impact/probability, assign mitigations, and review frequently."],
  ["what is stakeholder management", "Stakeholder management is aligning communication and expectations with people affected by a project."],
  ["what is customer persona", "A customer persona is a profile representing your ideal user segment and behavior."],
  ["what is user journey", "User journey maps how a person interacts with your product from discovery to retention."],
  ["what is retention metric", "Retention metric measures how many users return and keep using your product over time."],
  ["what is funnel analysis", "Funnel analysis tracks user drop-off across steps toward a goal."],
  ["what is market segmentation", "Market segmentation divides customers into groups with similar needs or behavior."],
  ["what is value proposition", "Value proposition explains why your solution is uniquely useful for customers."],
  ["how to write strong cv summary", "Write 2-4 lines showing your role, strengths, and measurable impact."],
  ["how to answer why should we hire you", "Link your proven results to the role needs and show clear fit."],
  ["how to improve linkedin profile", "Use a clear headline, measurable achievements, and keyword-rich experience."],
  ["how to ask for internship", "Send a concise message with your interest, skills, and request for opportunity."],
  ["what is financial statement", "Financial statements include income statement, balance sheet, and cash flow report."],
  ["what is gross margin", "Gross margin is revenue minus cost of goods sold, divided by revenue."],
  ["what is net margin", "Net margin is net profit divided by total revenue."],
  ["what is operating expense", "Operating expense is the day-to-day cost of running a business."],
  ["what is depreciation", "Depreciation spreads asset cost over its useful life for accounting purposes."],
  ["what is break even analysis", "Break-even analysis finds sales level where profit is zero."],
  ["how to prepare budget forecast", "Estimate revenue and costs by period, include assumptions, and compare vs actuals monthly."],
  ["what is supply chain", "Supply chain is the network from raw materials to final delivery to customers."],
  ["what is inventory turnover", "Inventory turnover shows how often stock is sold and replaced in a period."],
  ["how to reduce operating cost", "Cut low-value spend, improve process efficiency, and automate repetitive tasks."],
  ["what is customer support sla", "Support SLA defines expected response and resolution times for customer issues."],
  ["how to write policy document", "State purpose, scope, rules, responsibilities, and enforcement clearly."],
  ["what is governance", "Governance is the system of rules, roles, and oversight for decision-making."],
  ["what is compliance", "Compliance means following legal, regulatory, and internal policy requirements."],
  ["what is data privacy", "Data privacy governs how personal data is collected, used, shared, and protected."],
  ["what is gdpr", "GDPR is an EU regulation on personal data protection and privacy rights."],
  ["what is backup strategy", "Backup strategy defines how often data is copied, where it is stored, and recovery targets."],
  ["what is disaster recovery", "Disaster recovery restores systems and data after major outages or incidents."],
  ["what is rto and rpo", "RTO is maximum downtime target; RPO is maximum acceptable data loss window."],
  ["how to improve public speaking", "Structure your message, rehearse aloud, control pace, and engage audience with examples."],
  ["how to write persuasive proposal", "Focus on client pain, your solution, proof, timeline, and clear pricing."],
  ["what is persuasive communication", "Persuasive communication uses logic, emotion, and credibility to influence decisions."],
  ["how to build negotiation confidence", "Prepare your value, alternatives, and walk-away point before discussions."],
  ["what is mentorship", "Mentorship is guidance from an experienced person to support growth and decisions."],
  ["how to create learning plan", "Define goals, learning resources, timeline, and measurable milestones."],
  ["what is competency matrix", "A competency matrix maps required skills vs current skill levels."],
  ["how to lead without authority", "Influence through trust, expertise, collaboration, and clear communication."],
  ["what is systems thinking", "Systems thinking views problems as interconnected parts rather than isolated events."],
  ["how to make better strategic decisions", "Use data, scenarios, assumptions testing, and post-decision reviews."],
  ["what is scenario planning", "Scenario planning prepares strategies for multiple plausible future outcomes."],
  ["what is opportunity sizing", "Opportunity sizing estimates market and revenue potential for an idea."],
  ["what is service design", "Service design plans end-to-end customer experience across touchpoints."],
  ["what is design thinking", "Design thinking is a human-centered method: empathize, define, ideate, prototype, test."],
  ["how to run retrospective", "Discuss what went well, what did not, and concrete action items for improvement."],
];

module.exports = {
  PACK,
};
